### ISSUE TITLE
Common in WebUI in ClientApp?

### ISSUE THREAD

**Issue by hypervtechnics** [JasonGT/CleanArchitecture#10]
**Describe the bug**
The Common folder is inside of the ClientApp folder.

**To Reproduce**
Look at the structure.

**Expected behavior**
Shouldn't this one be in the root of the WebUI project?

**Screenshots**
*-*

**Additional context**
*-*

**Comment by Pyrobolser** [comment]
I think you are having an issue on your side.
On the GitHub repo and on my own version I see the **Common** folder and the **ClientApp** folder at the same level. Not one in the other.

**Comment by hypervtechnics** [comment]
Hm. Okay just cloned it again. Maybe I accidently moved it without noticing. Sorry for causing inconvenience.
