### ISSUE TITLE
Feature Request: Have all error responses follow the same pattern

### ISSUE THREAD

**Issue by TorbjornHoltmon** [JasonGT/CleanArchitecture#11]
**Is your feature request related to a problem? Please describe.**
A 400 response from /api/TodoList/{id} looks like:
``` js
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "Bad Request",
  "status": 400,
  "traceId": "|e46a85a0-4b31bf31a62d8f20."
}
```
A 404 response from /api/TodoList/{id} looks like:
``` js
{
  "error": "Entity \"TodoList\" (45) was not found."
}
```

In order to write global error handling on the client side I would have to write costum checks for all possible responses.

**Describe the solution you'd like**
What would make error handling on the client side very easy would be if all erros where formated something like:
``` js
{
"success": "false",
"error": "404",
"message": Entity \"TodoList\" (45) was not found."
}
```
**Describe alternatives you've considered**
Current alternative is to write custom handling for errors that does not give the response:
``` js
{
  "error": "Entity \"TodoList\" (45) was not found."
}
```

**Additional context**
I have none.

**Comment by hypervtechnics** [comment]
See #8 where I also wanted this.

**Comment by TorbjornHoltmon** [comment]
Duplicate of #8
