### ISSUE TITLE
404 Loading Favico

### ISSUE THREAD

**Issue by tparikka** [JasonGT/CleanArchitecture#17]
**Describe the bug**
A 404 occurs trying to load favico in Windows 10 Pro x64:

```Failed to load resource: the server responded with a status of 404 (Not Found) :52178/favicon.ico:1```

**To Reproduce**
1. Create a new project from the template per the directions in the readme.
2. Use dotnet run to initialize project
3. Load index in Chrome

**Expected behavior**
No 404s should occur on page load.

**Comment by JasonGT** [comment]
Thanks, I'll get it fixed.

**Comment by JasonGT** [comment]
Oh, wait - you loaded index.html in Chrome? If so, that's not the right approach.

After `dotnet run` the console will output: 

```
Hosting environment: Development
Content root path: C:\Code\Scratch\CaSln01\src\WebUI
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
```

You should then load **https://localhost:5001** in Chrome.

Now if you do that, the app will launch correctly and you won't see any 404 errors.

**Comment by tparikka** [comment]
Yup, that was the culprit. Thank you!
