### ISSUE TITLE
Clean Architecture template using .net Core 3.1

### ISSUE THREAD

**Issue by SuliemanMansouri** [JasonGT/CleanArchitecture#18]
**Describe the bug**
after installing Visual studio 16.4. the command 
dotnet new ca-sln will not work.
I reinstalled the template and was able to create a new project however the resulted solution is different it looks like it rolled back to 2.2 template, specifically in the Application folder.
The query and the handler are in a separate files and it does not use ProjectTo in LINQ.

**Comment by cuno92** [comment]
@SuliemanMansouri i think [this PR](https://github.com/JasonGT/CleanArchitecture/pull/21) may fix this issue. Can you fetch new changes and try again

**Comment by JasonGT** [comment]
I've just merged .NET Core 3.1 upgrade from @cuno92 so you should run into any more issues. Let me know how you go. Thanks.

**Comment by SuliemanMansouri** [comment]
I'll try the new template and keep you posted.

**Comment by SuliemanMansouri** [comment]
adding a controller will throw the following error

Error	MSB3073	The command "dotnet "C:\Users\Sulieman\.nuget\packages\nswag.msbuild\13.1.2\build\../tools/NetCore30/dotnet-nswag.dll" run /variables:Configuration=Debug" exited with code -1.	WebUI	C:\Users\Sulieman\Source\repos\SM.StudentRegistration\Src\WebUI\WebUI.csproj	60	

4>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
4>C:\Users\Sulieman\Source\repos\SM.StudentRegistration\Src\WebUI\WebUI.csproj(60,5): error MSB3073: The command "dotnet "C:\Users\Sulieman\.nuget\packages\nswag.msbuild\13.1.2\build\../tools/NetCore30/dotnet-nswag.dll" run /variables:Configuration=Debug" exited with code -1.

**Comment by JasonGT** [comment]
Do you have a repo I can take a look at?

**Comment by SuliemanMansouri** [comment]
I apologize for my last post, the wording of the problem was misleading. That's what you get when trying to code at 4am in the morning.
My issue was when trying to build the solution and generate the nswag code for angular was throwing the error, not adding the controller itself.

I am using TFVC as my repo. It turned out that I need to check-out my solution in order to successfully build, just checking out WebUI project was not enough for a successful build.

Thanks for the support

**Comment by JasonGT** [comment]
No worries at all, glad that you got it up and running. 😄

Happy coding!
