### ISSUE TITLE
[QUESTION] How to add migrations?

### ISSUE THREAD

**Issue by engineers-tools** [JasonGT/CleanArchitecture#33]
Hi Jason,
Thank you for this great project. I really like your concept of having the developer fall in a "pit of success".

I've been trying to use `dotnet ef` to add migrations but I get an error saying that the ApplicationDbContext cannot be created.

Is there a preferred/recommended way of doing this in this template?

**Comment by mhornbacher** [comment]
To elaborate on this, the issue with this template when it comes to migrations is the following:

If run from the Infrastructure project the following error occurs:

```
$ dotnet ef migrations add InitialCreate --project Infrastructure/
Build started...
Build succeeded.
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

If run from the WebUI project the following error occurs:

```
$ dotnet ef migrations add InitialCreate --project WebUI/
Build started...
Build succeeded.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: MigrationsAssembly=Cheder.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Your target project 'Cheder.WebUI' doesn't match your migrations assembly 'Cheder.Infrastructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Cheder.WebUI")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
```

Would it be possible for you to elaborate on what you did to create the initial migrations (specifically including the Identity one?)

Thank you!

**Comment by mhornbacher** [comment]
@engineers-tools Here is how to add migrations using this template:

1. install `dotnet-ef`
    1. `dotnet new tool-manifest` in the root of the repository
    2. `dotnet tool install dotnet-ef` in the same folder
2. run the following command to create a migration:
   - `dotnet ef migrations add MigrationName --project src/Infrastructure/ --startup-project src/WebUI/ --output-dir Persistence/Migrations/`

**Comment by engineers-tools** [comment]
@mhornbacher Thank you for the solution, it works like a charm

**Comment by mhornbacher** [comment]
Your welcome, glad I could help :-)
