### ISSUE TITLE
How to add migration?

### ISSUE THREAD

**Issue by dheltanumericz** [JasonGT/CleanArchitecture#47]
I am having error (_**Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728**_) when running "dotnet ef migrations add sampleMigation" inside the infrastructure project. Am I doing the right way?

Kindly advise.

Thanks!

**Comment by foondook** [comment]
@dheltanumericz you're doing it the right way, but you're missing the `DesignTimeDbContextFactory` EF can use for generating migrations.

The easiest is to refer to this code in another Jason's repo:
https://github.com/JasonGT/NorthwindTraders/blob/master/Src/Persistence/DesignTimeDbContextFactoryBase.cs

**Comment by alberthoekstra** [comment]
I execute this from the src folder:
```
dotnet ef migrations add REPLACE_WITH_NEW_NAME -p Infrastructure -s WebUI
```

**Comment by dheltanumericz** [comment]
Thank you @alberthoekstra @foondook. I was also able to create migrations using this command.

dotnet ef migrations add MIGRATION_NAME --startup-project=..\WebUI --output-dir=Persistence\Migrations --verbose
