### ISSUE TITLE
Why Mapping method with default implementation doesn't work ?

### ISSUE THREAD

**Issue by vnc4567** [JasonGT/CleanArchitecture#57]
Hello,

In the interface IMapFrom, there is a default implementation for the Mapping method 

```
public interface IMapFrom<T>
    {
        void Mapping(Profile profile) => profile.CreateMap(typeof(T), GetType());
    }
```

If I have a Class PersonVM which implements IMapFrom like this 

```
public class PersonVM : IMapFrom<Domain.Person>
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Email { get; set; }
		public int Age { get; set; }
     }

```
It will throw an exception at runtime : "The mapping between PersonVM and Domain.Person is not found."

It will work If I implement the interface IMapFrom like this :

```
	public class PersonVM : IMapFrom<Domain.Person>
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Email { get; set; }
		public int Age { get; set; }

		public void Mapping(Profile profile)
		{
			profile.CreateMap<Domain.Person, PersonVM>();	
		}
	}
```

Am I missing something? I don't want to implement a method Mapping() every time..

Thank you so much.

**Comment by JanOonk** [comment]
Will it help if you remove the **Domain.** namespace prefix before Person and include this namespace in the usings at the top?

**Comment by vnc4567** [comment]
Sorry, it's a mistake. The problem is in an other project (NorthwindTraders) The mapping profile is different in CleanArchitecture project and it works perfectly.
